// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2GXubltHQgFx8G3JoxNsDnrBlj3J7qKc',
    appId: '1:932119232004:web:7bb40f2893f59796b1ff51',
    messagingSenderId: '932119232004',
    projectId: 'yafa-b5643',
    authDomain: 'yafa-b5643.firebaseapp.com',
    databaseURL: 'https://yafa-b5643-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yafa-b5643.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB03T6BK1Jb768FzTLJ6731Sa4Bx3g3smg',
    appId: '1:932119232004:android:2d7489caa8d706cdb1ff51',
    messagingSenderId: '932119232004',
    projectId: 'yafa-b5643',
    databaseURL: 'https://yafa-b5643-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yafa-b5643.appspot.com',
  );
}
